# Railway Project Configuration
app = "reactivities0007"
primary_region = "sin"

[build]
  image = "gin0007/reactivities:latest"

[deploy]
  restart_policy = "always"  # Ensure the app restarts on failure

[env]
  ASPNETCORE_URLS = "https://+:8080"
  DOTNET_RUNNING_IN_CONTAINER = "true"
  DATABASE_URL = "postgresql://user:password@db-host:5432/dbname"  # Replace with actual Railway DB connection

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"  # Stops inactive instances
  auto_start_machines = true
  min_machines_running = 1  # Keeps at least one instance active
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[mounts]
  source = "pg_data"
  destination = "/var/lib/postgresql/data"

[services."postgres"]
  plan = "starter"  # Choose appropriate plan
  max_connections = 20  # Adjust based on load
  extensions = ["pgcrypto", "uuid-ossp"]  # Enable useful PostgreSQL extensions
